# This program says hello and asks for my name.
print("hello world")
print("what is your name")
myName =input()
print("nice to meet you " + myName)
print("the lenght of your name is ")
print(len(myName))
print("whats is your age ")
myAge =input()
print (" u will be " + str(int(myAge) + "1" ) + " in next year" )